### ISSUE TITLE
Asking about your NetShield_Protector 

### ISSUE THREAD

**Issue by modz2014** [AhmedMinegames/AntiCrack-DotNet#1]
hi man looking at your code i was wondering if you could add in a seperate code for once getting hardware id needs to be sent to someone and they will send it back to with a password to be out in before the app starts stop people from stealing i cant seem to find anything free and open source

**Comment by AhmedMinegames** [comment]
okay... firstly why you are making an issue here and not on NetShield Respiratory? secondly yeah i can add that, but you will have to get a DNS (like NO-IP) which when i add that it will gonna ask for your DNS and then embeed it in the packed program and try to contact your program using TCP to get the key, and i will make a seperate secure program which will gonna be the host which will manage the key's and hosts but all of that will take time specially that i'm working alone, and my exams are getting soon, so don't excpect an update to come soon.

**Comment by modz2014** [comment]
i couldn't open a issue yesterday saying you archived the project sorry

is there a reason why NetShield doesnt create the license.dat file when you add the license and protect it not license.dat file is created

**Comment by modz2014** [comment]
can we also add both license hard drive check as well

**Comment by AhmedMinegames** [comment]
for License.dat you can change it's name to whatever you want, and for the license file you can create it yourself.
